# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

R: Sim

In [14]:
Cachorros = ["Minnie", "Loki", "Chaplin", "Mancha"]
Gatos = ["Banana", "Layla", "Rafir", "Leo"]
Pessoas = ["Palhaça", "Minha_Mi", "Ma", "Tita"]
Animais_porpessoas = [0, 2, 2, 4]
Tem_animais = [False, True, True, True]
na_casa = {"Cachorros": Cachorros,
           "Gatos": Gatos,
           "Pessoas": Pessoas,
           "Animais_porpessoas": Animais_porpessoas,
           "Tem_animais": Tem_animais}
Matriz = [
    [Cachorros, Gatos],
    [Pessoas, Animais_porpessoas]
]
Matriz
Matriz.insert(4,Tem_animais)
Matriz

[[['Minnie', 'Loki', 'Chaplin', 'Mancha'],
  ['Banana', 'Layla', 'Rafir', 'Leo']],
 [['Palhaça', 'Minha_Mi', 'Ma', 'Tita'], [0, 2, 2, 4]],
 [False, True, True, True]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [15]:
PPARG_1 = "PPARG"
PPARG_car = len(PPARG_1)
PPARG_in = [PPARG_1 [0], PPARG_1[1]]
PPARG_a = PPARG_1.count("A")
PPARG_hu = "hu" in PPARG_1
PPARG_list = [PPARG_car, PPARG_in, PPARG_a, PPARG_hu]
PPARG_list

[5, ['P', 'P'], 1, False]

In [16]:
ADRB2_1 = "ADRB2"
ADRB2_car = len(ADRB2_1)
ADRB2_in = [ADRB2_1 [0], ADRB2_1[1]]
ADRB2_a = ADRB2_1.count("A")
ADRB2_hu = "hu" in ADRB2_1
ADRB2_list = [ADRB2_car, ADRB2_in, ADRB2_a, ADRB2_hu]
ADRB2_list

[5, ['A', 'D'], 1, False]

In [19]:
DMT2_1 = "DMT2"
DMT2_car = len(DMT2_1)
DMT2_in = [DMT2_1 [0], DMT2_1[1]]
DMT2_a = DMT2_1.count("A")
DMT2_hu = "hu" in DMT2_1
DMT2_list = [DMT2_car, DMT2_in, DMT2_a, DMT2_hu]
DMT2_list

[4, ['D', 'M'], 0, False]

In [17]:
FABP2_1 = "FABP2"
FABP2_car = len(FABP2_1)
FABP2_in = [FABP2_1 [0], FABP2_1[1]]
FABP2_a = FABP2_1.count("A")
FABP2_hu = "hu" in FABP2_1
FABP2_list = [FABP2_car, FABP2_in, FABP2_a, FABP2_hu]
FABP2_list

[5, ['F', 'A'], 1, False]

In [3]:
MCR4_1 = "MCR4"
MCR4_car = len(MCR4_1)
MCR4_in = [MCR4_1 [0], MCR4_1[1]]
MCR4_a = MCR4_1.count("A")
MCR4_hu = "hu" in MCR4_1
MCR4_list = [MCR4_car, MCR4_in, MCR4_a, MCR4_hu]
MCR4_list

[4, ['M', 'C'], 0, False]

In [20]:
genes_newlist = [PPARG_list, ADRB2_list, DMT2_list, FABP2_list, MCR4_list,]
genes_newlist

[[5, ['P', 'P'], 1, False],
 [5, ['A', 'D'], 1, False],
 [4, ['D', 'M'], 0, False],
 [5, ['F', 'A'], 1, False],
 [4, ['M', 'C'], 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [21]:
import numpy as np
import pandas as pd

In [22]:
PPARG_ = ["PPARG", 5, "PP", 0, False]
ADRB2_ = ["ADRB2", 5, "AD", 1, False]
DMT2_ = ["DMT2", 4, "DM", 0, False] 
FABP2_ = ["FABP2", 5, "FA", 1, False]
MCR4_ = ["MCR4", 4, "MC", 0, False]
genes_lista = [PPARG_, ADRB2_, DMT2_, FABP2_, MCR4_]
genes_lista

[['PPARG', 5, 'PP', 0, False],
 ['ADRB2', 5, 'AD', 1, False],
 ['DMT2', 4, 'DM', 0, False],
 ['FABP2', 5, 'FA', 1, False],
 ['MCR4', 4, 'MC', 0, False]]

In [23]:
array = np.array(genes_lista)
array

array([['PPARG', '5', 'PP', '0', 'False'],
       ['ADRB2', '5', 'AD', '1', 'False'],
       ['DMT2', '4', 'DM', '0', 'False'],
       ['FABP2', '5', 'FA', '1', 'False'],
       ['MCR4', '4', 'MC', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [24]:
array[2,:]

array(['DMT2', '4', 'DM', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [25]:
array[:,0]
"hu" in array[:,0]

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [26]:
SQ = [array[1,:], array[3,:]]
SQ
Doisp = array[:,2]
Doisp
QA = array[:,3]
QA
Resp6 = [SQ, Doisp, QA]
Resp6

[[array(['ADRB2', '5', 'AD', '1', 'False'], dtype='<U21'),
  array(['FABP2', '5', 'FA', '1', 'False'], dtype='<U21')],
 array(['PP', 'AD', 'DM', 'FA', 'MC'], dtype='<U21'),
 array(['0', '1', '0', '1', '0'], dtype='<U21')]

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [28]:
Genes = {
    "PPARG": PPARG_list,
    "ADRB2": ADRB2_list,
    "DMT2": DMT2_list,
    "FABP2": FABP2_list,
    "MCR4": MCR4_list
    }
df = pd.DataFrame(Genes)
df
df = df.T
df.columns = ["num_Caracteres", "Iniciais", "Count_A", "tem_hu"]
df.to_csv("df.csv")
df

      num_Caracteres Iniciais Count_A tem_hu
PPARG              5   [P, P]       1  False
ADRB2              5   [A, D]       1  False
DMT2               4   [D, M]       0  False
FABP2              5   [F, A]       1  False
MCR4               4   [M, C]       0  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [29]:
df.loc[:, ["num_Caracteres", "Count_A"]]

      num_Caracteres Count_A
PPARG              5       1
ADRB2              5       1
DMT2               4       0
FABP2              5       1
MCR4               4       0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [30]:
df.loc[["PPARG", "DMT2"], ["tem_hu"]]

      tem_hu
PPARG  False
DMT2   False

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [31]:
df = pd.read_csv("data.csv")
df

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [72]:
estat = df.describe()
estat

,policyID,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,point_granularity
count,36634.000000,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000
mean,548661.937189,7.314780e+05,2.074348e+06,6.646009e+05,9.911724e+05,2.172875e+06,2.571004e+06,7.787908e+02,7.037985e+03,192.453210,26.483594,28.087477,-81.903565,1.640907
std,259912.926494,1.752300e+07,1.964150e+07,1.746114e+07,1.767178e+07,2.015015e+07,2.036777e+07,4.787979e+04,9.582593e+04,8037.713716,4702.740932,1.647734,1.809066,1.070561
min,100074.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+01,7.337000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,24.547514,-87.447290,1.000000
25%,323647.750000,0.000000e+00,4.248106e+04,0.000000e+00,0.000000e+00,4.562415e+04,5.401351e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,26.471996,-82.439331,1.000000
50%,548525.000000,0.000000e+00,1.926911e+05,0.000000e+00,0.000000e+00,2.021051e+05,2.416310e+05,0.000000e+00,0.000000e+00,0.000000,0.000000,28.057077,-81.585700,1.000000
75%,774252.000000,0.000000e+00,9.163381e+05,0.000000e+00,5.741010e+04,9.465821e+05,1.128871e+06,0.000000e+00,0.000000e+00,0.000000,0.000000,29.623005,-80.372910,3.000000
max,999971.000000,2.160000e+09,2.160000e+09,2.160000e+09,2.160000e+09,2.160000e+09,1.701000e+09,6.273765e+06,7.380000e+06,450000.000000,900000.000000,30.989820,-80.033257,7.000000

In [60]:
#número de entradas = número de linhas
entradas = df.shape[0]
entradas

36634

In [32]:
Classes = list(df.dtypes)
Classes

[dtype('int64'),
 dtype('O'),
 dtype('O'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('O'),
 dtype('O'),
 dtype('int64')]

In [69]:
QClasses = [df.dtypes.value_counts()]
QClasses

[float64    11
 object      4
 int64       3
 Name: count, dtype: int64]

In [ ]:
Mean = [estat.loc["mean", :]]
Mean

policyID              5.486619e+05
eq_site_limit         7.314780e+05
hu_site_limit         2.074348e+06
fl_site_limit         6.646009e+05
fr_site_limit         9.911724e+05
tiv_2011              2.172875e+06
tiv_2012              2.571004e+06
eq_site_deductible    7.787908e+02
hu_site_deductible    7.037985e+03
fl_site_deductible    1.924532e+02
fr_site_deductible    2.648359e+01
point_latitude        2.808748e+01
point_longitude      -8.190357e+01
point_granularity     1.640907e+00
Name: mean, dtype: float64

In [79]:
Std = [estat.loc["std", :]]
Std

[policyID              2.599129e+05
 eq_site_limit         1.752300e+07
 hu_site_limit         1.964150e+07
 fl_site_limit         1.746114e+07
 fr_site_limit         1.767178e+07
 tiv_2011              2.015015e+07
 tiv_2012              2.036777e+07
 eq_site_deductible    4.787979e+04
 hu_site_deductible    9.582593e+04
 fl_site_deductible    8.037714e+03
 fr_site_deductible    4.702741e+03
 point_latitude        1.647734e+00
 point_longitude       1.809066e+00
 point_granularity     1.070561e+00
 Name: std, dtype: float64]

In [80]:
Tquartil = [estat.loc["75%", ["policyID", "hu_site_limit", "hu_site_deductible"]]]
Tquartil

[policyID              774252.00
 hu_site_limit         916338.06
 hu_site_deductible         0.00
 Name: 75%, dtype: float64]

In [83]:
R10 = {
    "Entradas" : entradas,
    "Classes" : Classes,
    "QClases" : QClasses,
    "Mean" : Mean,
    "Std" : Std,
    "Tquartil" : Tquartil}
R10

{'Entradas': 36634,
 'Classes': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'QClases': [float64    11
  object      4
  int64       3
  Name: count, dtype: int64],
 'Mean': policyID              5.486619e+05
 eq_site_limit         7.314780e+05
 hu_site_limit         2.074348e+06
 fl_site_limit         6.646009e+05
 fr_site_limit         9.911724e+05
 tiv_2011              2.172875e+06
 tiv_2012              2.571004e+06
 eq_site_deductible    7.787908e+02
 hu_site_deductible    7.037985e+03
 fl_site_deductible    1.924532e+02
 fr_site_deductible    2.648359e+01
 point_latitude        2.808748e+01
 point_longitude      -8.190357e+01
 point_granularity     1.640907e+00
 Name: mean, dtype: float64,
 'Std': [policyID              2.599129e+05
  eq_site_limit         1.752300e+07
  hu_site_limit         1.964150e+07
  fl_site_limit         1.746114e+07
  fr_site_limit         1.767178e+07
  tiv_2011              2.015015e+07
  tiv_2012              2.036777e+07
  eq_site_deductible    4.787979e+04
  hu_site_deductible    9.582593e+04
  fl_site_deductible    8.037714e+03
  fr_site_deductible    4.702741e+03
  point_latitude        1.647734e+00
  point_longitude       1.809066e+00
  point_granularity     1.070561e+00
  Name: std, dtype: float64],
 'Tquartil': [policyID              774252.00
  hu_site_limit         916338.06
  hu_site_deductible         0.00
  Name: 75%, dtype: float64]}