# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [38]:
import numpy as np
import pandas as pd
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2
print(p)
print(q)
print(r)
print(s)
print(t)

False
True
True
True
False

In [7]:
print(f"{not p}")
print(f"{not q}")
print(f"{not r}")
print(f"{not s}")
print(f"{not t}")

True
False
False
False
True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [18]:
#não entendi bem se o objetivo era trocar a operação por OR ou se era pra usar or pra entender se tudo era 1 or 0
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]
print(p)
print(q)
print(r)
print(s)
print(t)
print(u)

False
True
False
True
False
True

In [19]:
print(p or q or r or s or t or u)

True

In [22]:
print(not (p or q or r or s or t or u))

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [26]:
import pandas as pd
df3 = pd.read_csv("comp_1.csv", index_col="Unnamed: 0")
df3 = df3.round(3)
df3

                   ultima_linha  ultima_coluna
numero_de_valores         4.000          7.000
media                    25.407         34.590
std                      10.603         29.495
min                      16.224          5.292
25%                      16.224         11.828
50%                      25.407         34.590
75%                      34.590         45.795
max                      34.590         87.000

In [63]:
l2 = df3.iloc[1,:]
l3 =  df3.iloc[2,:]
l4 =  df3.iloc[3,:]
l1 = df3.iloc[0,:]
l5 = df3.iloc[4,:]
l6 = df3.iloc[5,:]
l7 = df3.iloc[6,:]
l7 = df3.iloc[7,:]
c2 = df3.iloc[:,1]
print(l2)
print(l3)
print(l4)

ultima_linha     25.407
ultima_coluna    34.590
Name: media, dtype: float64
ultima_linha     10.603
ultima_coluna    29.495
Name: std, dtype: float64
ultima_linha     16.224
ultima_coluna     5.292
Name: min, dtype: float64

In [51]:
#print((l2 == l3).all() (l3 == l4).all())???????
print(l2.equals(l3) or l3.equals(l4))
print(l2.equals(l3))
print(l3.equals(l4))

False
False
False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [53]:
print((l2 > 10).all())

True

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [ ]:
#no data frame importado não tem terceira coluna...
print(((c2 > 0) & (c2 < 40)).all())

False

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [64]:
print((l8 > 10).any())

True

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [69]:
df_mask = df3.where((df3 > 5) & (df3 < 7))
df_mask = df_mask.fillna(0)
df_mask

                   ultima_linha  ultima_coluna
numero_de_valores           0.0          0.000
media                       0.0          0.000
std                         0.0          0.000
min                         0.0          5.292
25%                         0.0          0.000
50%                         0.0          0.000
75%                         0.0          0.000
max                         0.0          0.000

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [71]:
df_mask2 = df3.where((df3 >= 5) & (df3 <= 7))
df_mask2 = df_mask2.fillna(0)
df_mask2

                   ultima_linha  ultima_coluna
numero_de_valores           0.0          7.000
media                       0.0          0.000
std                         0.0          0.000
min                         0.0          5.292
25%                         0.0          0.000
50%                         0.0          0.000
75%                         0.0          0.000
max                         0.0          0.000

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [76]:
import numpy as np
import pandas as pd
C1 = df3.iloc[:,0]
C2 = df3.iloc[:,1]
C1array = np.array(C1)
C2array = np.array(C2)
print(C1array)
print(C2array)
print(((C1array >= 2) & (C1array <= 40)).any())

[ 4.    25.407 10.603 16.224 16.224 25.407 34.59  34.59 ]
[ 7.    34.59  29.495  5.292 11.828 34.59  45.795 87.   ]
True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [77]:
print(((C1array >= -(1)) & (C1array <= 12)).all())

False