# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
2 == 2.0
3 == 3.0
5 == 5.0
10.2 == 10.2
33.8 == 33.8
a = 18
b = 32
c = 57
d = 28
Resp_a = 2 + 3/5
Resp_a

2.6

In [2]:
Resp_b = (a + 10.2) - 5 * 2
Resp_b

18.2

In [3]:
Resp_c = a/b + 33.8
Resp_c

34.3625

In [4]:
Resp_d = a / (b + c)
Resp_d

0.20224719101123595

In [5]:
Resp_e = d * 2
Resp_e

56

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [6]:
2 == 2.0
3 == 3.0
5 == 5.0
10 == 10
20 == 20
30 == 30
lista_a = ["cha", "chocolate_quente", "guarana", "café"]
lista_b = ["bolinho_de_chuva", "rabanada", "torta_de_maça", "bolo"]
lista_c = ["tapioca", "pao", "torrada", "biscoito"]

In [7]:
Respo_a = [2.0, 3.0, 5.0] + [10, 20, 30]
Respo_a

[2.0, 3.0, 5.0, 10, 20, 30]

In [8]:
Respo_b = lista_a * 2
Respo_b

['cha',
 'chocolate_quente',
 'guarana',
 'café',
 'cha',
 'chocolate_quente',
 'guarana',
 'café']

In [9]:
Respo_c = lista_a + lista_b
Respo_c

['cha',
 'chocolate_quente',
 'guarana',
 'café',
 'bolinho_de_chuva',
 'rabanada',
 'torta_de_maça',
 'bolo']

In [12]:
Respo_d = lista_a / (lista_b * lista_c)
Respo_d

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [13]:
a = 18
b = 32
c = 57
d = 28
e = 87
list_ex1 = [a, b, c, d, e]
list_ex1

[18, 32, 57, 28, 87]

In [14]:
list_raiz = [x**0.5 for x in list_ex1]
list_raiz

[4.242640687119285,
 5.656854249492381,
 7.54983443527075,
 5.291502622129181,
 9.327379053088816]

In [15]:
import numpy as np
lista_ex1 = np.array([a, b, c, d, e])
raizes = [np.sqrt(lista_ex1)]
raizes

[array([4.24264069, 5.65685425, 7.54983444, 5.29150262, 9.32737905])]

In [16]:
soma_list = list_raiz+list_ex1
soma_list

[4.242640687119285,
 5.656854249492381,
 7.54983443527075,
 5.291502622129181,
 9.327379053088816,
 18,
 32,
 57,
 28,
 87]

In [17]:
import pandas as pd
df1 = pd.DataFrame(list_ex1)
df2= pd.DataFrame(list_raiz)
Conc_list = pd.concat([df1, df2], axis=0)
Conc_list

           0
0  18.000000
1  32.000000
2  57.000000
3  28.000000
4  87.000000
0   4.242641
1   5.656854
2   7.549834
3   5.291503
4   9.327379

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [18]:
Dup = [soma_list * 2]
Dup
ex4 = np.array(Dup)
ex4
ex4 = ex4.reshape(5,4)
ex4

array([[ 4.24264069,  5.65685425,  7.54983444,  5.29150262],
       [ 9.32737905, 18.        , 32.        , 57.        ],
       [28.        , 87.        ,  4.24264069,  5.65685425],
       [ 7.54983444,  5.29150262,  9.32737905, 18.        ],
       [32.        , 57.        , 28.        , 87.        ]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [19]:
#axis 0 = colunas (y) e axis 1 = linhas(x)
media = np.mean(ex4, axis=0)
media

array([16.22397084, 34.58967137, 16.22397084, 34.58967137])

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [20]:
ex4.shape
# se o shape = 5,4 então o número de valores são 5*4 = 20

(5, 4)

In [23]:
ex4 = np.append(ex4, media)

In [ ]:
soma_list.append(media)
soma_list

[4.242640687119285,
 5.656854249492381,
 7.54983443527075,
 5.291502622129181,
 9.327379053088816,
 18,
 32,
 57,
 28,
 87,
 array([16.22397084, 34.58967137, 16.22397084, 34.58967137]),
 array([16.22397084, 34.58967137, 16.22397084, 34.58967137]),
 array([16.22397084, 34.58967137, 16.22397084, 34.58967137])]

In [ ]:
array = np.array(ex4)
list6 = media
array
media
novo_array = np.append(array, list6)
novo_array

array([ 4.24264069,  5.65685425,  7.54983444,  5.29150262,  9.32737905,
       18.        , 32.        , 57.        , 28.        , 87.        ,
        4.24264069,  5.65685425,  7.54983444,  5.29150262,  9.32737905,
       18.        , 32.        , 57.        , 28.        , 87.        ,
       16.22397084, 34.58967137, 16.22397084, 34.58967137])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [ ]:
novo_array.shape
novo_array.reshape(6,4)

array([[ 4.24264069,  5.65685425,  7.54983444,  5.29150262],
       [ 9.32737905, 18.        , 32.        , 57.        ],
       [28.        , 87.        ,  4.24264069,  5.65685425],
       [ 7.54983444,  5.29150262,  9.32737905, 18.        ],
       [32.        , 57.        , 28.        , 87.        ],
       [16.22397084, 34.58967137, 16.22397084, 34.58967137]])

In [ ]:
novo_array = pd.DataFrame(novo_array)
novo_array = round (novo_array,3)
novo_array
novo_array

        0       1       2       3
0   4.243   5.657   7.550   5.292
1   9.327  18.000  32.000  57.000
2  28.000  87.000   4.243   5.657
3   7.550   5.292   9.327  18.000
4  32.000  57.000  28.000  87.000
5  16.224  34.590  16.224  34.590

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [ ]:
list8 = media
list8
df8 = pd.DataFrame(list8)
novo_array = pd.DataFrame(novo_array)
novo_array = round (novo_array,3)
novo_array
df8_1 = np.append(novo_array,df8)
df8_1
#fica retornando para a forma array e não dataframe
df8_2 = pd.DataFrame(df8_1.reshape(-1,4))
df8_2
#agora os números não estão mais arredondados mas não era o objetivo

           0          1          2          3
0   4.243000   5.657000   7.550000   5.292000
1   9.327000  18.000000  32.000000  57.000000
2  28.000000  87.000000   4.243000   5.657000
3   7.550000   5.292000   9.327000  18.000000
4  32.000000  57.000000  28.000000  87.000000
5  16.224000  34.590000  16.224000  34.590000
6  16.223971  34.589671  16.223971  34.589671

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [ ]:
ultlinha = df8_2.iloc[-1]
ultlinha
ultcoluna = df8_2.iloc[:, -1]
ultcoluna
descultlinha = ultlinha.describe()
descultcoluna = ultcoluna.describe()
comp = [descultlinha, descultcoluna]
comp = pd.DataFrame(comp)
comp
comp_1 =comp.T
comp_1

               6          3
count   4.000000   7.000000
mean   25.406821  34.589810
std    10.603442  29.495015
min    16.223971   5.292000
25%    16.223971  11.828500
50%    25.406821  34.589671
75%    34.589671  45.795000
max    34.589671  87.000000

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
comp_1.columns = ["ultima_linha", "ultima_coluna"]
comp_1.index = [
    "numero_de_valores",
    "media",
    "std",
    "min",
    "25%",
    "50%",
    "75%",
    "max"
]
comp_1

                   ultima_linha  ultima_coluna
numero_de_valores      4.000000       7.000000
media                 25.406821      34.589810
std                   10.603442      29.495015
min                   16.223971       5.292000
25%                   16.223971      11.828500
50%                   25.406821      34.589671
75%                   34.589671      45.795000
max                   34.589671      87.000000

In [ ]:
# a última linha é a linha das médias, por isso, a média das médias seria a média da última linha 
comp_1.loc["media", "ultima_linha"]
#ou se quiser a média entre as médias da última linha e última coluna

np.float64(25.40682110471004)

In [ ]:
comp_1.to_csv("comp_1.csv")